#!/bin/bash
# Shows the IP address of the first active interface
IP=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'`
IF=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $8}'`
echo -e "Interface: ${IF}"
echo -e "IP: ${IP}"
